//@version=5
indicator(title="Relative Strength Index - Divergences", shorttitle="RSI Div")
len = input.int(14, minval=1, title="RSI Length")
ob = input.int(defval=70, title="Overbought", minval=0, maxval=100)
os_ = input.int(defval=30, title="Oversold", minval=0, maxval=100)
omid = input.int(defval=50, title="Midline value", minval=0, maxval=100)
omidh = input.bool(false, title="Hide midline")

// RSI code
rsi = ta.rsi(close, len)
band1 = hline(ob)
band0 = hline(os_)
band3 = hline(omid, color=color.new(color.black, omidh ? 100 : 80))
plot(rsi, color=(rsi > ob or rsi < os_ ? color.new(color.yellow, 10) : color.new(color.yellow, 0)))
fill(band3, band1, color=color.new(color.lime, 96))
fill(band0, band3, color=color.new(color.red, 96))

// DIVS code
piv = input.bool(false, "Hide pivots?")
shrt = input.bool(false, "Shorter labels?")
hidel = input.bool(false, "Hide labels and color background")
xbars = input.int(defval=90, title="Div lookback period (bars)?", minval=1)
obos_only = input.bool(defval=false, title="Only divergences in OB/OS zones?")
hb = math.abs(ta.highestbars(rsi, xbars)) // Finds bar with highest value in last X bars
lb = math.abs(ta.lowestbars(rsi, xbars))  // Finds bar with lowest value in last X bars

// Defining variable values
max = float(na)
max_rsi = float(na)
min = float(na)
min_rsi = float(na)
pivoth = bool(na)
pivotl = bool(na)
divbear = bool(na)
divbull = bool(na)

// If bar with lowest / highest is current bar, use it's value
max := hb == 0 ? close : na(max[1]) ? close : max[1]
max_rsi := hb == 0 ? rsi : na(max_rsi[1]) ? rsi : max_rsi[1]
min := lb == 0 ? close : na(min[1]) ? close : min[1]
min_rsi := lb == 0 ? rsi : na(min_rsi[1]) ? rsi : min_rsi[1]

// Compare high of current bar being examined with previous bar's high
if close > max
    max := close
if rsi > max_rsi
    max_rsi := rsi
if close < min
    min := close
if rsi < min_rsi
    min_rsi := rsi

// Finds pivot point with at least 2 right candles with lower value
pivoth := (max_rsi == max_rsi[2]) and (max_rsi[2] != max_rsi[3]) ? true : na
pivotl := (min_rsi == min_rsi[2]) and (min_rsi[2] != min_rsi[3]) ? true : na

// Detects divergences between price and indicator with 1 candle delay
if (max[1] > max[2]) and (rsi[1] < max_rsi) and (rsi <= rsi[1])
    if not obos_only or max_rsi >= ob
        divbear := true
if (min[1] < min[2]) and (rsi[1] > min_rsi) and (rsi >= rsi[1])
    if not obos_only or min_rsi <= os_
        divbull := true

// Alerts
alertcondition(divbear, title='Bear div', message='Bear div')
alertcondition(divbull, title='Bull div', message='Bull div')
alertcondition(pivoth, title='Pivot high', message='Pivot high')
alertcondition(pivotl, title='Pivot low', message='Pivot low')

// Plots divergences and pivots with offset
l = divbear ?
       label.new(bar_index - 1, rsi[1] + 1, "BEAR", color=color.red, textcolor=color.white, style=label.style_label_down, yloc=yloc.price, size=size.small) :
       divbull ?
           label.new(bar_index - 1, rsi[1] - 1, "BULL", color=color.green, textcolor=color.white, style=label.style_label_up, yloc=yloc.price, size=size.small) :
           pivoth ?
               label.new(bar_index - 2, max_rsi + 1, "PIVOT", color=color.blue, textcolor=color.white, style=label.style_label_down, yloc=yloc.price, size=size.small) :
               pivotl ?
                   label.new(bar_index - 2, min_rsi - 1, "PIVOT", color=color.blue, textcolor=color.white, style=label.style_label_up, yloc=yloc.price, size=size.small) :
                   na

// Shorter labels
if shrt
    label.set_text(l, na)
// Hides pivots or labels
if (piv and (pivoth or pivotl)) or hidel
    label.delete(l)
// Colors indicator background
bgcolor(hidel ? (divbear ? color.new(color.red, 50) : divbull ? color.new(color.green, 50) : na) : na, offset=-1)
bgcolor(hidel ? (piv ? na : (pivoth or pivotl ? color.new(color.blue, 50) : na)) : na, offset=-2)

// Debug tools
// plot(max, color=color.blue, linewidth=2)
// plot(max_rsi, color=color.red, linewidth=2)
// plot(hb, color=color.orange, linewidth=2)
// plot(lb, color=color.purple, linewidth=1)
// plot(min_rsi, color=color.lime, linewidth=1)
// plot(min, color=color.black, linewidth=1)
